<!DOCTYPE html>
<html>
<head>
<title>Angular Directive comment</title>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
</head>
<body ng-app="myApp">

<!-- directive: w3-test-directive -->
<script>
var app = angular.module("myApp", []);
app.directive("w3TestDirective", function(){
	return{
		restrict : "M",
		replace : true,
		template : "<h1>Generated by a directive!</h1>"
	};
});
</script>

<p><strong>Note:</strong> We added the <strong>replace</strong> property in this example, otherwise the comment would be invisible.</p>

<p><strong>Note:</strong> You must add the value of "M" to the <strong>restrict</strong>  property to be able to invoke the directive from the comment.</p>
</body>
</html>